//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public int cityId { get; set; }
        public string cityName { get; set; }
        public int stateId { get; set; }
    }
}
