//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDemoJQueryForm
    {
        public string Code { get; set; }
        public System.DateTime DOB { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public int id { get; set; }
        public int Salary { get; set; }
        public int State { get; set; }
        public int City { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
